/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedUsersRouteImport } from './routes/_protected/users'
import { Route as ProtectedGenerateRouteImport } from './routes/_protected/generate'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAdduserRouteImport } from './routes/_protected/adduser'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGenerateRoute = ProtectedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdduserRoute = ProtectedAdduserRouteImport.update({
  id: '/adduser',
  path: '/adduser',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/adduser': typeof ProtectedAdduserRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/generate': typeof ProtectedGenerateRoute
  '/users': typeof ProtectedUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/adduser': typeof ProtectedAdduserRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/generate': typeof ProtectedGenerateRoute
  '/users': typeof ProtectedUsersRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/adduser': typeof ProtectedAdduserRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/generate': typeof ProtectedGenerateRoute
  '/_protected/users': typeof ProtectedUsersRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/adduser'
    | '/dashboard'
    | '/generate'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/adduser'
    | '/dashboard'
    | '/generate'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/register'
    | '/_protected/adduser'
    | '/_protected/dashboard'
    | '/_protected/generate'
    | '/_protected/users'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/generate': {
      id: '/_protected/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof ProtectedGenerateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/adduser': {
      id: '/_protected/adduser'
      path: '/adduser'
      fullPath: '/adduser'
      preLoaderRoute: typeof ProtectedAdduserRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdduserRoute: typeof ProtectedAdduserRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedGenerateRoute: typeof ProtectedGenerateRoute
  ProtectedUsersRoute: typeof ProtectedUsersRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdduserRoute: ProtectedAdduserRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedGenerateRoute: ProtectedGenerateRoute,
  ProtectedUsersRoute: ProtectedUsersRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
